/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'body' : string,
  'creatorId' : UserId,
  'timestamp' : Time,
  'targetGroups' : Array<ERPRole>,
}
export type AnnouncementId = bigint;
export interface Assessment {
  'id' : AssessmentId,
  'title' : string,
  'maxPoints' : bigint,
  'type' : { 'final' : null } |
    { 'assignment' : null } |
    { 'test' : null },
  'classId' : ClassId,
  'weights' : number,
}
export type AssessmentId = bigint;
export interface AttendanceRecord {
  'status' : { 'present' : null } |
    { 'late' : null } |
    { 'absent' : null } |
    { 'excused' : null },
  'studentId' : UserId,
  'date' : Time,
  'classId' : ClassId,
  'notes' : [] | [string],
}
export interface Book {
  'id' : BookId,
  'title' : string,
  'isbn' : string,
  'author' : string,
  'available' : boolean,
}
export type BookId = bigint;
export type ClassId = bigint;
export interface ClassSection {
  'id' : ClassId,
  'timetable' : Array<string>,
  'name' : string,
  'grade' : bigint,
  'teacherId' : UserId,
}
export type ERPRole = { 'accountant' : null } |
  { 'principal' : null } |
  { 'librarian' : null } |
  { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export type ExternalBlob = Uint8Array;
export interface Fee {
  'id' : FeeStructureId,
  'status' : { 'pending' : null } |
    { 'paid' : null } |
    { 'overdue' : null },
  'studentId' : UserId,
  'dueDate' : Time,
  'stripeSessionId' : [] | [string],
  'amount' : bigint,
}
export type FeeStructureId = bigint;
export interface Grade {
  'studentId' : UserId,
  'assessmentId' : AssessmentId,
  'points' : bigint,
}
export interface Profile {
  'id' : UserId,
  'gpa' : number,
  'status' : { 'active' : null } |
    { 'inactive' : null } |
    { 'graduated' : null },
  'name' : string,
  'classId' : [] | [ClassId],
  'photo' : [] | [ExternalBlob],
  'parentId' : [] | [UserId],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'erpRoles' : Array<ERPRole>,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<[string, string, string], BookId>,
  'addGrade' : ActorMethod<[UserId, AssessmentId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignERPRole' : ActorMethod<[Principal, ERPRole], undefined>,
  'calculateStudentGpa' : ActorMethod<[UserId], number>,
  'checkoutBook' : ActorMethod<[BookId, UserId], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, Array<ERPRole>],
    AnnouncementId
  >,
  'createAssessment' : ActorMethod<
    [
      ClassId,
      string,
      { 'final' : null } |
        { 'assignment' : null } |
        { 'test' : null },
      bigint,
      number,
    ],
    AssessmentId
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createClassSection' : ActorMethod<
    [string, bigint, Array<string>, Principal],
    ClassId
  >,
  'createFee' : ActorMethod<[UserId, bigint, Time], FeeStructureId>,
  'getAllClassSections' : ActorMethod<[], Array<ClassSection>>,
  'getAllStudents' : ActorMethod<[], Array<Profile>>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAssessmentsForClass' : ActorMethod<[ClassId], Array<Assessment>>,
  'getAttendance' : ActorMethod<[UserId], Array<AttendanceRecord>>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckedOutBooks' : ActorMethod<[], Array<[BookId, UserId]>>,
  'getClassSection' : ActorMethod<[ClassId], ClassSection>,
  'getFees' : ActorMethod<[UserId], Array<Fee>>,
  'getGrades' : ActorMethod<[UserId], Array<Grade>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudent' : ActorMethod<[UserId], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [
      ClassId,
      Array<
        [
          UserId,
          { 'present' : null } |
            { 'late' : null } |
            { 'absent' : null } |
            { 'excused' : null },
        ]
      >,
    ],
    undefined
  >,
  'markFeePaid' : ActorMethod<[UserId, FeeStructureId], undefined>,
  'registerStudent' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [UserId], [] | [ClassId]],
    undefined
  >,
  'returnBook' : ActorMethod<[BookId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateStudentStatus' : ActorMethod<
    [
      UserId,
      { 'active' : null } |
        { 'inactive' : null } |
        { 'graduated' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];