/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookId = IDL.Nat;
export const UserId = IDL.Principal;
export const AssessmentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ERPRole = IDL.Variant({
  'accountant' : IDL.Null,
  'principal' : IDL.Null,
  'librarian' : IDL.Null,
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const AnnouncementId = IDL.Nat;
export const ClassId = IDL.Nat;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const FeeStructureId = IDL.Nat;
export const ClassSection = IDL.Record({
  'id' : ClassId,
  'timetable' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'grade' : IDL.Nat,
  'teacherId' : UserId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'id' : UserId,
  'gpa' : IDL.Float64,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'graduated' : IDL.Null,
  }),
  'name' : IDL.Text,
  'classId' : IDL.Opt(ClassId),
  'photo' : IDL.Opt(ExternalBlob),
  'parentId' : IDL.Opt(UserId),
});
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'creatorId' : UserId,
  'timestamp' : Time,
  'targetGroups' : IDL.Vec(ERPRole),
});
export const Assessment = IDL.Record({
  'id' : AssessmentId,
  'title' : IDL.Text,
  'maxPoints' : IDL.Nat,
  'type' : IDL.Variant({
    'final' : IDL.Null,
    'assignment' : IDL.Null,
    'test' : IDL.Null,
  }),
  'classId' : ClassId,
  'weights' : IDL.Float64,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
    'excused' : IDL.Null,
  }),
  'studentId' : UserId,
  'date' : Time,
  'classId' : ClassId,
  'notes' : IDL.Opt(IDL.Text),
});
export const Book = IDL.Record({
  'id' : BookId,
  'title' : IDL.Text,
  'isbn' : IDL.Text,
  'author' : IDL.Text,
  'available' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'erpRoles' : IDL.Vec(ERPRole),
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Fee = IDL.Record({
  'id' : FeeStructureId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  }),
  'studentId' : UserId,
  'dueDate' : Time,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const Grade = IDL.Record({
  'studentId' : UserId,
  'assessmentId' : AssessmentId,
  'points' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BookId], []),
  'addGrade' : IDL.Func([UserId, AssessmentId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignERPRole' : IDL.Func([IDL.Principal, ERPRole], [], []),
  'calculateStudentGpa' : IDL.Func([UserId], [IDL.Float64], ['query']),
  'checkoutBook' : IDL.Func([BookId, UserId], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ERPRole)],
      [AnnouncementId],
      [],
    ),
  'createAssessment' : IDL.Func(
      [
        ClassId,
        IDL.Text,
        IDL.Variant({
          'final' : IDL.Null,
          'assignment' : IDL.Null,
          'test' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Float64,
      ],
      [AssessmentId],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createClassSection' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Principal],
      [ClassId],
      [],
    ),
  'createFee' : IDL.Func([UserId, IDL.Nat, Time], [FeeStructureId], []),
  'getAllClassSections' : IDL.Func([], [IDL.Vec(ClassSection)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAssessmentsForClass' : IDL.Func(
      [ClassId],
      [IDL.Vec(Assessment)],
      ['query'],
    ),
  'getAttendance' : IDL.Func([UserId], [IDL.Vec(AttendanceRecord)], ['query']),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckedOutBooks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(BookId, UserId))],
      ['query'],
    ),
  'getClassSection' : IDL.Func([ClassId], [ClassSection], ['query']),
  'getFees' : IDL.Func([UserId], [IDL.Vec(Fee)], ['query']),
  'getGrades' : IDL.Func([UserId], [IDL.Vec(Grade)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStudent' : IDL.Func([UserId], [Profile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [
        ClassId,
        IDL.Vec(
          IDL.Tuple(
            UserId,
            IDL.Variant({
              'present' : IDL.Null,
              'late' : IDL.Null,
              'absent' : IDL.Null,
              'excused' : IDL.Null,
            }),
          )
        ),
      ],
      [],
      [],
    ),
  'markFeePaid' : IDL.Func([UserId, FeeStructureId], [], []),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(UserId), IDL.Opt(ClassId)],
      [],
      [],
    ),
  'returnBook' : IDL.Func([BookId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateStudentStatus' : IDL.Func(
      [
        UserId,
        IDL.Variant({
          'active' : IDL.Null,
          'inactive' : IDL.Null,
          'graduated' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookId = IDL.Nat;
  const UserId = IDL.Principal;
  const AssessmentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ERPRole = IDL.Variant({
    'accountant' : IDL.Null,
    'principal' : IDL.Null,
    'librarian' : IDL.Null,
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const AnnouncementId = IDL.Nat;
  const ClassId = IDL.Nat;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const FeeStructureId = IDL.Nat;
  const ClassSection = IDL.Record({
    'id' : ClassId,
    'timetable' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'grade' : IDL.Nat,
    'teacherId' : UserId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'id' : UserId,
    'gpa' : IDL.Float64,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'inactive' : IDL.Null,
      'graduated' : IDL.Null,
    }),
    'name' : IDL.Text,
    'classId' : IDL.Opt(ClassId),
    'photo' : IDL.Opt(ExternalBlob),
    'parentId' : IDL.Opt(UserId),
  });
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'creatorId' : UserId,
    'timestamp' : Time,
    'targetGroups' : IDL.Vec(ERPRole),
  });
  const Assessment = IDL.Record({
    'id' : AssessmentId,
    'title' : IDL.Text,
    'maxPoints' : IDL.Nat,
    'type' : IDL.Variant({
      'final' : IDL.Null,
      'assignment' : IDL.Null,
      'test' : IDL.Null,
    }),
    'classId' : ClassId,
    'weights' : IDL.Float64,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Variant({
      'present' : IDL.Null,
      'late' : IDL.Null,
      'absent' : IDL.Null,
      'excused' : IDL.Null,
    }),
    'studentId' : UserId,
    'date' : Time,
    'classId' : ClassId,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Book = IDL.Record({
    'id' : BookId,
    'title' : IDL.Text,
    'isbn' : IDL.Text,
    'author' : IDL.Text,
    'available' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'erpRoles' : IDL.Vec(ERPRole),
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Fee = IDL.Record({
    'id' : FeeStructureId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'overdue' : IDL.Null,
    }),
    'studentId' : UserId,
    'dueDate' : Time,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const Grade = IDL.Record({
    'studentId' : UserId,
    'assessmentId' : AssessmentId,
    'points' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BookId], []),
    'addGrade' : IDL.Func([UserId, AssessmentId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignERPRole' : IDL.Func([IDL.Principal, ERPRole], [], []),
    'calculateStudentGpa' : IDL.Func([UserId], [IDL.Float64], ['query']),
    'checkoutBook' : IDL.Func([BookId, UserId], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ERPRole)],
        [AnnouncementId],
        [],
      ),
    'createAssessment' : IDL.Func(
        [
          ClassId,
          IDL.Text,
          IDL.Variant({
            'final' : IDL.Null,
            'assignment' : IDL.Null,
            'test' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Float64,
        ],
        [AssessmentId],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createClassSection' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Principal],
        [ClassId],
        [],
      ),
    'createFee' : IDL.Func([UserId, IDL.Nat, Time], [FeeStructureId], []),
    'getAllClassSections' : IDL.Func([], [IDL.Vec(ClassSection)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAssessmentsForClass' : IDL.Func(
        [ClassId],
        [IDL.Vec(Assessment)],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [UserId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckedOutBooks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(BookId, UserId))],
        ['query'],
      ),
    'getClassSection' : IDL.Func([ClassId], [ClassSection], ['query']),
    'getFees' : IDL.Func([UserId], [IDL.Vec(Fee)], ['query']),
    'getGrades' : IDL.Func([UserId], [IDL.Vec(Grade)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStudent' : IDL.Func([UserId], [Profile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [
          ClassId,
          IDL.Vec(
            IDL.Tuple(
              UserId,
              IDL.Variant({
                'present' : IDL.Null,
                'late' : IDL.Null,
                'absent' : IDL.Null,
                'excused' : IDL.Null,
              }),
            )
          ),
        ],
        [],
        [],
      ),
    'markFeePaid' : IDL.Func([UserId, FeeStructureId], [], []),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(UserId), IDL.Opt(ClassId)],
        [],
        [],
      ),
    'returnBook' : IDL.Func([BookId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateStudentStatus' : IDL.Func(
        [
          UserId,
          IDL.Variant({
            'active' : IDL.Null,
            'inactive' : IDL.Null,
            'graduated' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };