/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    id: UserId;
    gpa: number;
    status: Variant_active_inactive_graduated;
    name: string;
    classId?: ClassId;
    photo?: ExternalBlob;
    parentId?: UserId;
}
export type AssessmentId = bigint;
export interface Grade {
    studentId: UserId;
    assessmentId: AssessmentId;
    points: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Announcement {
    id: AnnouncementId;
    title: string;
    body: string;
    creatorId: UserId;
    timestamp: Time;
    targetGroups: Array<ERPRole>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface AttendanceRecord {
    status: Variant_present_late_absent_excused;
    studentId: UserId;
    date: Time;
    classId: ClassId;
    notes?: string;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ClassId = bigint;
export type BookId = bigint;
export interface ClassSection {
    id: ClassId;
    timetable: Array<string>;
    name: string;
    grade: bigint;
    teacherId: UserId;
}
export interface Assessment {
    id: AssessmentId;
    title: string;
    maxPoints: bigint;
    type: Variant_final_assignment_test;
    classId: ClassId;
    weights: number;
}
export interface Fee {
    id: FeeStructureId;
    status: Variant_pending_paid_overdue;
    studentId: UserId;
    dueDate: Time;
    stripeSessionId?: string;
    amount: bigint;
}
export type FeeStructureId = bigint;
export interface Book {
    id: BookId;
    title: string;
    isbn: string;
    author: string;
    available: boolean;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type AnnouncementId = bigint;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    erpRoles: Array<ERPRole>;
    email?: string;
    phone?: string;
}
export enum ERPRole {
    accountant = "accountant",
    principal = "principal",
    librarian = "librarian",
    admin = "admin",
    teacher = "teacher",
    student = "student",
    parent = "parent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_inactive_graduated {
    active = "active",
    inactive = "inactive",
    graduated = "graduated"
}
export enum Variant_final_assignment_test {
    final_ = "final",
    assignment = "assignment",
    test = "test"
}
export enum Variant_pending_paid_overdue {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum Variant_present_late_absent_excused {
    present = "present",
    late = "late",
    absent = "absent",
    excused = "excused"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBook(title: string, author: string, isbn: string): Promise<BookId>;
    addGrade(studentId: UserId, assessmentId: AssessmentId, points: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignERPRole(user: Principal, role: ERPRole): Promise<void>;
    calculateStudentGpa(studentId: UserId): Promise<number>;
    checkoutBook(bookId: BookId, studentId: UserId): Promise<void>;
    createAnnouncement(title: string, body: string, targetGroups: Array<ERPRole>): Promise<AnnouncementId>;
    createAssessment(classId: ClassId, title: string, type: Variant_final_assignment_test, maxPoints: bigint, weights: number): Promise<AssessmentId>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createClassSection(name: string, grade: bigint, timetable: Array<string>, teacherId: Principal): Promise<ClassId>;
    createFee(studentId: UserId, amount: bigint, dueDate: Time): Promise<FeeStructureId>;
    getAllClassSections(): Promise<Array<ClassSection>>;
    getAllStudents(): Promise<Array<Profile>>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getAssessmentsForClass(classId: ClassId): Promise<Array<Assessment>>;
    getAttendance(studentId: UserId): Promise<Array<AttendanceRecord>>;
    getBooks(): Promise<Array<Book>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckedOutBooks(): Promise<Array<[BookId, UserId]>>;
    getClassSection(classId: ClassId): Promise<ClassSection>;
    getFees(studentId: UserId): Promise<Array<Fee>>;
    getGrades(studentId: UserId): Promise<Array<Grade>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStudent(studentId: UserId): Promise<Profile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markAttendance(classId: ClassId, records: Array<[UserId, Variant_present_late_absent_excused]>): Promise<void>;
    markFeePaid(studentId: UserId, feeId: FeeStructureId): Promise<void>;
    registerStudent(name: string, photo: ExternalBlob | null, parentId: UserId | null, classId: ClassId | null): Promise<void>;
    returnBook(bookId: BookId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateStudentStatus(studentId: UserId, status: Variant_active_inactive_graduated): Promise<void>;
}
import type { Announcement as _Announcement, AnnouncementId as _AnnouncementId, Assessment as _Assessment, AssessmentId as _AssessmentId, AttendanceRecord as _AttendanceRecord, ClassId as _ClassId, ERPRole as _ERPRole, ExternalBlob as _ExternalBlob, Fee as _Fee, FeeStructureId as _FeeStructureId, Profile as _Profile, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBook(arg0: string, arg1: string, arg2: string): Promise<BookId> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, arg2);
            return result;
        }
    }
    async addGrade(arg0: UserId, arg1: AssessmentId, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGrade(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGrade(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignERPRole(arg0: Principal, arg1: ERPRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignERPRole(arg0, to_candid_ERPRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignERPRole(arg0, to_candid_ERPRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateStudentGpa(arg0: UserId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateStudentGpa(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateStudentGpa(arg0);
            return result;
        }
    }
    async checkoutBook(arg0: BookId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutBook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutBook(arg0, arg1);
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: Array<ERPRole>): Promise<AnnouncementId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createAssessment(arg0: ClassId, arg1: string, arg2: Variant_final_assignment_test, arg3: bigint, arg4: number): Promise<AssessmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssessment(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssessment(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createClassSection(arg0: string, arg1: bigint, arg2: Array<string>, arg3: Principal): Promise<ClassId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClassSection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClassSection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createFee(arg0: UserId, arg1: bigint, arg2: Time): Promise<FeeStructureId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFee(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFee(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllClassSections(): Promise<Array<ClassSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClassSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClassSections();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssessmentsForClass(arg0: ClassId): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessmentsForClass(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessmentsForClass(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendance(arg0: UserId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooks();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckedOutBooks(): Promise<Array<[BookId, UserId]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckedOutBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckedOutBooks();
            return result;
        }
    }
    async getClassSection(arg0: ClassId): Promise<ClassSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassSection(arg0);
            return result;
        }
    }
    async getFees(arg0: UserId): Promise<Array<Fee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFees(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFees(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrades(arg0: UserId): Promise<Array<Grade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrades(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrades(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: UserId): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Profile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Profile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markAttendance(arg0: ClassId, arg1: Array<[UserId, Variant_present_late_absent_excused]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async markFeePaid(arg0: UserId, arg1: FeeStructureId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFeePaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFeePaid(arg0, arg1);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: ExternalBlob | null, arg2: UserId | null, arg3: ClassId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, await to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, await to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async returnBook(arg0: BookId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.returnBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnBook(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateStudentStatus(arg0: UserId, arg1: Variant_active_inactive_graduated): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentStatus(arg0, to_candid_variant_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentStatus(arg0, to_candid_variant_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Announcement_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Assessment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assessment): Assessment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ERPRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ERPRole): ERPRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Fee_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fee): Fee {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassId]): ClassId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    gpa: number;
    status: {
        active: null;
    } | {
        inactive: null;
    } | {
        graduated: null;
    };
    name: string;
    classId: [] | [_ClassId];
    photo: [] | [_ExternalBlob];
    parentId: [] | [_UserId];
}): Promise<{
    id: UserId;
    gpa: number;
    status: Variant_active_inactive_graduated;
    name: string;
    classId?: ClassId;
    photo?: ExternalBlob;
    parentId?: UserId;
}> {
    return {
        id: value.id,
        gpa: value.gpa,
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        name: value.name,
        classId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.classId)),
        photo: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.photo)),
        parentId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnnouncementId;
    title: string;
    body: string;
    creatorId: _UserId;
    timestamp: _Time;
    targetGroups: Array<_ERPRole>;
}): {
    id: AnnouncementId;
    title: string;
    body: string;
    creatorId: UserId;
    timestamp: Time;
    targetGroups: Array<ERPRole>;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        creatorId: value.creatorId,
        timestamp: value.timestamp,
        targetGroups: from_candid_vec_n25(_uploadFile, _downloadFile, value.targetGroups)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssessmentId;
    title: string;
    maxPoints: bigint;
    type: {
        final: null;
    } | {
        assignment: null;
    } | {
        test: null;
    };
    classId: _ClassId;
    weights: number;
}): {
    id: AssessmentId;
    title: string;
    maxPoints: bigint;
    type: Variant_final_assignment_test;
    classId: ClassId;
    weights: number;
} {
    return {
        id: value.id,
        title: value.title,
        maxPoints: value.maxPoints,
        type: from_candid_variant_n31(_uploadFile, _downloadFile, value.type),
        classId: value.classId,
        weights: value.weights
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        present: null;
    } | {
        late: null;
    } | {
        absent: null;
    } | {
        excused: null;
    };
    studentId: _UserId;
    date: _Time;
    classId: _ClassId;
    notes: [] | [string];
}): {
    status: Variant_present_late_absent_excused;
    studentId: UserId;
    date: Time;
    classId: ClassId;
    notes?: string;
} {
    return {
        status: from_candid_variant_n35(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        classId: value.classId,
        notes: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    erpRoles: Array<_ERPRole>;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    erpRoles: Array<ERPRole>;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        erpRoles: from_candid_vec_n25(_uploadFile, _downloadFile, value.erpRoles),
        email: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeStructureId;
    status: {
        pending: null;
    } | {
        paid: null;
    } | {
        overdue: null;
    };
    studentId: _UserId;
    dueDate: _Time;
    stripeSessionId: [] | [string];
    amount: bigint;
}): {
    id: FeeStructureId;
    status: Variant_pending_paid_overdue;
    studentId: UserId;
    dueDate: Time;
    stripeSessionId?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n45(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        dueDate: value.dueDate,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.stripeSessionId)),
        amount: value.amount
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    graduated: null;
}): Variant_active_inactive_graduated {
    return "active" in value ? Variant_active_inactive_graduated.active : "inactive" in value ? Variant_active_inactive_graduated.inactive : "graduated" in value ? Variant_active_inactive_graduated.graduated : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    principal: null;
} | {
    librarian: null;
} | {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
}): ERPRole {
    return "accountant" in value ? ERPRole.accountant : "principal" in value ? ERPRole.principal : "librarian" in value ? ERPRole.librarian : "admin" in value ? ERPRole.admin : "teacher" in value ? ERPRole.teacher : "student" in value ? ERPRole.student : "parent" in value ? ERPRole.parent : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    final: null;
} | {
    assignment: null;
} | {
    test: null;
}): Variant_final_assignment_test {
    return "final" in value ? Variant_final_assignment_test.final : "assignment" in value ? Variant_final_assignment_test.assignment : "test" in value ? Variant_final_assignment_test.test : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} | {
    excused: null;
}): Variant_present_late_absent_excused {
    return "present" in value ? Variant_present_late_absent_excused.present : "late" in value ? Variant_present_late_absent_excused.late : "absent" in value ? Variant_present_late_absent_excused.absent : "excused" in value ? Variant_present_late_absent_excused.excused : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): Variant_pending_paid_overdue {
    return "pending" in value ? Variant_pending_paid_overdue.pending : "paid" in value ? Variant_pending_paid_overdue.paid : "overdue" in value ? Variant_pending_paid_overdue.overdue : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Promise<Array<Profile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Profile_n15(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ERPRole>): Array<ERPRole> {
    return value.map((x)=>from_candid_ERPRole_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assessment>): Array<Assessment> {
    return value.map((x)=>from_candid_Assessment_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fee>): Array<Fee> {
    return value.map((x)=>from_candid_Fee_n43(_uploadFile, _downloadFile, x));
}
function to_candid_ERPRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ERPRole): _ERPRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassId | null): [] | [_ClassId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    erpRoles: Array<ERPRole>;
    email?: string;
    phone?: string;
}): {
    name: string;
    erpRoles: Array<_ERPRole>;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        erpRoles: to_candid_vec_n12(_uploadFile, _downloadFile, value.erpRoles),
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_tuple_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [UserId, Variant_present_late_absent_excused]): [_UserId, {
        present: null;
    } | {
        late: null;
    } | {
        absent: null;
    } | {
        excused: null;
    }] {
    return [
        value[0],
        to_candid_variant_n51(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ERPRole): {
    accountant: null;
} | {
    principal: null;
} | {
    librarian: null;
} | {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
} {
    return value == ERPRole.accountant ? {
        accountant: null
    } : value == ERPRole.principal ? {
        principal: null
    } : value == ERPRole.librarian ? {
        librarian: null
    } : value == ERPRole.admin ? {
        admin: null
    } : value == ERPRole.teacher ? {
        teacher: null
    } : value == ERPRole.student ? {
        student: null
    } : value == ERPRole.parent ? {
        parent: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_final_assignment_test): {
    final: null;
} | {
    assignment: null;
} | {
    test: null;
} {
    return value == Variant_final_assignment_test.final ? {
        final_: null
    } : value == Variant_final_assignment_test.assignment ? {
        assignment: null
    } : value == Variant_final_assignment_test.test ? {
        test: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_present_late_absent_excused): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} | {
    excused: null;
} {
    return value == Variant_present_late_absent_excused.present ? {
        present: null
    } : value == Variant_present_late_absent_excused.late ? {
        late: null
    } : value == Variant_present_late_absent_excused.absent ? {
        absent: null
    } : value == Variant_present_late_absent_excused.excused ? {
        excused: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_inactive_graduated): {
    active: null;
} | {
    inactive: null;
} | {
    graduated: null;
} {
    return value == Variant_active_inactive_graduated.active ? {
        active: null
    } : value == Variant_active_inactive_graduated.inactive ? {
        inactive: null
    } : value == Variant_active_inactive_graduated.graduated ? {
        graduated: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ERPRole>): Array<_ERPRole> {
    return value.map((x)=>to_candid_ERPRole_n10(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[UserId, Variant_present_late_absent_excused]>): Array<[_UserId, {
        present: null;
    } | {
        late: null;
    } | {
        absent: null;
    } | {
        excused: null;
    }]> {
    return value.map((x)=>to_candid_tuple_n50(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
